### ISSUE TITLE
Failed installing depency iohook

### ISSUE THREAD

**Issue by vDimatrix** [Xn2/osuListMaker#4]
Hey there, I really like the way this should work. My problem is by doing "npm install" the iohook package won't install and gives out an error message.

The error message:
```
Prebuild for current platform (iohook-v0.6.1-node-v83-win32-x64) not found!
(Use `node --trace-uncaught ...` to show where the exception was thrown)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iohook@0.6.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iohook@0.6.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
is there any other way to run the program without installing the iohook package?

Dimatrix

**Comment by Xn2** [comment]
iohook is the package that handles keyboard shortcuts outside of the focus of the application, without it, you will not be able to trigger the function that sends the song data to the Google API.

What OS are you running the script from ?

**Comment by vDimatrix** [comment]
Windows 10

**Comment by Xn2** [comment]
Okay, I have been able to replicate the issue on my end. The package.json contains a version number that does not exist anymore on iohook's repo.

I have been able to install it directly via npm by running the command `npm i iohook` in the same folder as you would normally run `npm install`.

**Comment by vDimatrix** [comment]
Oh my, it works, even tho this is the first time I'm doing something like this!
Thank you so much for this program, your help and the really quick replies!
